name: fmbp
description: Enterprise Application

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.3+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  badges: ^2.0.3
  camera: ^0.10.0+3
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  date_format: ^2.0.6
  easy_localization: ^3.0.1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.4.3+8
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.5
  flutter_slidable: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_widget_from_html_core: ^0.8.5+3
  http: ^0.13.4
  image_picker: ^0.8.5+3
  location: ^4.4.0
  path: ^1.8.1
  path_provider: ^2.0.9
  permission_handler: ^10.0.2
  persistent_bottom_nav_bar: ^4.0.2
  shared_preferences: ^2.0.15
  table_calendar: ^3.0.6
  grouped_list: ^5.1.2

flutter_icons:
  image_path: assets/app_icon/logo.png
  # image_path_android: assets/launcher/ic.png
  android: true
  ios: true

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
#setting cho splash screen
flutter_native_splash:
  color: "#00864a"
  image: assets/images/splash_logo.png
  color_dark: "#00864a"
  image_dark: assets/images/splash_logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
    - assets/lang/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato2OFL/Lato-Regular.ttf
        - asset: assets/fonts/Lato2OFL/Lato-Bold.ttf
          weight: 700
